# Usamos Python 3.12 (ajustar según tu versión)
FROM python:3.12-slim

# Definimos el directorio de trabajo
WORKDIR /app

# Copiamos Pipfile y Pipfile.lock para instalar dependencias
COPY Pipfile Pipfile.lock ./

# Instalamos pipenv
RUN pip install pipenv

# Instalamos dependencias en modo production
RUN pipenv install --system --deploy

# Copiamos el resto del backend
COPY . .

# Exponemos el puerto del backend
EXPOSE 8000

# Comando por defecto
CMD ["python3", "__main__.py"]
